### PR TITLE
Bug 1967369: Merge upstream tag v1.8.2

### PR DESCRIPTION
**Pull request by jmrodri**
Merge upstream tag v1.8.2

Operator SDK v1.8.2

Merge executed via ./UPSTREAM-MERGE.sh v1.8.2 upstream release-4.8

Overwritten conflicts:
<NONE>

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/approve

**Comment by dhellmann** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.80

picked

**Pull request merged**
