### PR TITLE
OCPBUGS-30459: Bump `google.golang.org/protobuf`

### PR DESCRIPTION
**Pull request by m1kola**
**Description of the change:**

Bumps `google.golang.org/protobuf`

**Motivation for the change:**

Adresses https://pkg.go.dev/vuln/GO-2024-2611

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
/lgtm
/approve
(Though I may not have permission)

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Comment by grokspawn** [comment]
no docs/px/qe blast radius for a minor-version dependencybump
/label docs-approved
/label px-approved
/label qe-approved

**Pull request merged**
