### PR TITLE
OCPBUGS-36458: Rename Dockerfile

### PR DESCRIPTION
**Pull request by ashwindasr**
Refactor name to `Dockerfile.ocp` as a better, version independent, alternative since contents are actually rhel9. 

CI: https://github.com/openshift/release/pull/53937

Please follow up with other changes in this/other repos if necessary. ART has setup the necessary [fallbacks](https://github.com/openshift-eng/ocp-build-data/pull/5039), but only for 4.17, if backporting this PR, please give us a heads up.

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm
/approve

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved
no need docs so,
/label docs-approved

**Pull request merged**
