### PR TITLE
OCPBUGS-34461,OCPBUGS-34327,OCPBUGS-34253: ART bumps

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
Combination of ART bump PRs to resolve test failures:
https://github.com/openshift/ocp-release-operator-sdk/pull/379
https://github.com/openshift/ocp-release-operator-sdk/pull/377
https://github.com/openshift/ocp-release-operator-sdk/pull/378

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by oceanc80 — APPROVED** [review]

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Pull request merged**
