### PR TITLE
Update python and ansible, remove preview image

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
- Updates Ansible to 2.15.0
- Limits dependencies we manage by only including in the Pipfile:
  - ansible-core
  - ansible-runner
  - ansible-runner-http
  - kubernetes
  - urllib3 (need to pin this to a version <2 due to some issues encountered when running the testdata/ansible/memcached-operator with these changes)
- Updates Python to 3.9 (minimum supported by Ansible 2.15.0)
- Removes the ansible-2.11-preview image
- Updates the base.Dockerfile to use multi-stage builds where Rust is installed before installing necessary python packages so that any architecture that may be missing prebuilt wheels can have the wheels built during the image build process.
 
**Motivation for the change:**
- Prevent users from using out of date and no longer supported ansible, python packages, and ansible collections

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — COMMENTED** [review]
I think a lot (if not all) of the changes to things outside the `release/ansible` folder will end being synced downstream with the next upstream SDK release (v1.31.0). To prevent sync issues due to divergence I think we should hold this PR until v1.31.0 is downstreamed and then rebase this PR against the `master` branch.

/hold

**Comment by leifmadsen** [comment]
> I think a lot (if not all) of the changes to things outside the `release/ansible` folder will end being synced downstream with the next upstream SDK release (v1.31.0). To prevent sync issues due to divergence I think we should hold this PR until v1.31.0 is downstreamed and then rebase this PR against the `master` branch.
> 
> /hold

Yea I just noticed that this is changing 410 files. That seems like a lot :)_

**Review by everettraven — APPROVED** [review]
These changes seem good to me. Looks like majority of the changes are now the vendored ansible collections which appear up to date

/lgtm

**Comment by leifmadsen** [comment]
I'm a bit confused about the 391 changed files. Is this typical, or is a rebase required here?

**Comment by everettraven** [comment]
>I'm a bit confused about the 391 changed files. Is this typical, or is a rebase required here?

@leifmadsen I _think_ this is typical since we updated some dependencies that are required to be vendored in. I don't think the vendoring will be necessary once the cachito stuff is in but if I understand correctly in the meantime we need to still vendor the new versions in.

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Pull request merged**
