### PR TITLE
Bug 1793309: internal/scaffold: don't change /etc/passwd perms [release-4.3]

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Cherry-pick: https://github.com/operator-framework/operator-sdk/pull/2469/files

**Motivation**
https://bugzilla.redhat.com/show_bug.cgi?id=1793309
Bug 1793309

### CODE REVIEW

**Comment by joelanford** [comment]
/retitle Bug 1793309: internal/scaffold: don't change /etc/passwd perms [release-4.3]

**Comment by camilamacedo86** [comment]
CI shows not passing because of:  https://github.com/openshift/sdn/pull/103

**Comment by fabianvf** [comment]
Looks like the failure was due to the SDN issue in the default namespace

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley, 

Could you please add here the label  `cherry-pick-approved` or we are able to move forward?

**Pull request merged**
