### PR TITLE
OCPBUGS-5429: [release-4.12] Merge upstream tag v1.25.1

### PR DESCRIPTION
**Pull request by everettraven**
This is a manual cherry-pick of #288 to `release-4.12` branch.

**Reason for manual cherry-pick**: There seems to be an issue with the vendor files in the automated cherry-pick PR #289 . I don't have permissions to push the fix from running `go mod vendor`, so in an effort to expedite the process I created this branch from the cherry pick bots branch.

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/approve
/lgtm

**Comment by emmajiafan** [comment]
@everettraven  Others looks good except the file "UPSTREAM-VERSION" is still 1.25.0

**Comment by everettraven** [comment]
@emmajiafan I updated the `UPSTREAM-VERSION` file as of commit https://github.com/openshift/ocp-release-operator-sdk/pull/296/commits/0625fc5dfa18f22e1863d55483b962bb4daeb24f

**Comment by everettraven** [comment]
@emmajiafan Are you able to add the `cherry-pick-approved` label?

**Review by KeenonLee — COMMENTED** [review]
/label cherry-pick-approved

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Pull request merged**
