### PR TITLE
[release-4.13] OCPBUGS-27534,OCPBUGS-27554,OCPBUGS-27559,OCPBUGS-27619,OCPBUGS-27639,OCPBUGS-27644: bump github.com/go-git/go-git/v5 to v5.11.0

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
This is a cherry-pick of https://github.com/openshift/ocp-release-operator-sdk/pull/364

**Motivation for the change:**
Addresses the following CVEs:

https://github.com/advisories/GHSA-mw99-9chc-xw7r
https://github.com/advisories/GHSA-449p-3h89-pw88 

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by theishshah — APPROVED** [review]
/lgtm

**Comment by KeenonLee** [comment]
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test-vm/52846/testReport/
pre merge testing

**Review by KeenonLee — COMMENTED** [review]
/label cherry-pick-approved

**Pull request merged**
