### PR TITLE
Bug 1956382: Merge upstream tag v1.6.2

### PR DESCRIPTION
**Pull request by theishshah**
Merge upstream tag v1.6.2

Operator SDK v1.6.2

Merge executed via ./UPSTREAM-MERGE.sh v1.6.2 upstream master

Overwritten conflicts:
hack/generate/samples/internal/ansible/testdata/build/Dockerfile

### CODE REVIEW

**Comment by jmrodri** [comment]
/retitle Bug 1956382: Merge upstream tag v1.6.2

**Review by jmrodri — APPROVED** [review]
/lgtm

**Comment by emmajiafan** [comment]
[1957725](https://bugzilla.redhat.com/show_bug.cgi?id=1957725)
[1958078](https://bugzilla.redhat.com/show_bug.cgi?id=1958078)
The story OSDK-1622 ([pkgman-to-bundle](https://github.com/operator-framework/operator-sdk/pull/4718)) is not in https://github.com/openshift/ocp-release-operator-sdk/pull/112

**Pull request merged**
