### PR TITLE
OCPBUGS-6744: Merge upstream tag v1.25.4 to release-4.12

### PR DESCRIPTION
**Pull request by rashmigottipati**
This PR is to downstream the upstream Operator-SDK v1.25.4 patch release to the release-4.12 branch.

Merge executed via `./UPSTREAM-MERGE.sh v1.25.4 release-4.12`

Patches verified via `make -f ci/prow.Makefile patch build`

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
These changes look good to me! Great work @rashmigottipati !

Holding LGTM on QE & Docs review first

**Comment by jmrodri** [comment]
@rashmigottipati looks great. Nicely done.

**Comment by rashmigottipati** [comment]
@emmajiafan could you also please add the `backport-risk-assessed` label as well?

cc @oceanc80

**Pull request merged**
