### PR TITLE
V0.17.1 merge

### PR DESCRIPTION
**Pull request by fabianvf**
**Description of the change:**

**Motivation for the change:**

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

This doesn't have a chance to PASS right now. The issue was [raised on Slack](https://coreos.slack.com/archives/CBN38N3MW/p1590628855159000) to which I responded:

> The one notable difference between the jobs that pass and the one that fails is that the failing one runs on the 4.4 build cluster and the passing ones run on the 3.11 one. So this is probably caused by the differences in how builds work between versions.

Once this problem is resolved this can be unheld.

**Comment by fabianvf** [comment]
There is no valid BZ for this

**Pull request merged**
