### PR TITLE
remove dependabot

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
Removes dependabot.yml from this repo to prevent Dependabot from making PRs in this repo.

**Motivation for the change:**
Dependabot changes will all be handled upstream and will be synced here. Dependabot does not need to be enabled on this repository.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by rashmigottipati — COMMENTED** [review]
/ok-to-test

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
merging this without QE, Docs and PX acks because this is just an internal maintenance item.

**Pull request merged**
