### PR TITLE
OCPBUGS-21586: [release-4.13] rapid reset CVE fix

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
- Replaces k8s packages with https://github.com/openshift/kubernetes/commit/c7606e743ff1b002c11b4d72da2add10d2057a9d
  - Uses this commit because this is a commit on the `release-4.13` branch which corresponds to the 1.26.z k8s packages which are still used here on `master`
- Bumps `golang.org/x/net` to `v0.17.0`
- `go mod tidy`
- `go mod vendor`

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
