### PR TITLE
OCPBUGS-21152: [release-4.10] rapid reset CVE fix

### PR DESCRIPTION
**Pull request by everettraven**
**Description of the change:**
- Replaces k8s packages with https://github.com/openshift/kubernetes/commit/9d53ff09a877c7aed7b649651f0f821d065864c5
  - Uses this commit because this is a commit on the `release-4.10` branch which corresponds to the 1.23.z k8s packages which are used here
- Bumps `golang.org/x/net` to `v0.17.0`
- `go mod tidy`
- `go mod vendor`
- Any other dependency changes necessary to facilitate the above changes were also made.
- Update unit tests failing from ginkgo issue from the 4.11 fix PR: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ocp-release-operator-sdk/345/pull-ci-openshift-ocp-release-operator-sdk-release-4.11-unit/1713959953674276864

### CODE REVIEW

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved
/label cherry-pick-approved

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Review by KeenonLee — COMMENTED** [review]
/jira refresh

**Pull request merged**
