### PR TITLE
Update ocp-release-operator-sdk to 4.1feature freeze version

### PR DESCRIPTION
**Pull request by shawn-hurley**

### CODE REVIEW

**Comment by joelanford** [comment]
@shawn-hurley I was comparing operator-sdk `v0.7.0` with this branch and noticed that downstream uses a `DelegatingClient` for the [Ansible](https://github.com/openshift/ocp-release-operator-sdk/blob/233dbad303edd3e6ad8e40fec92e31552e558319/pkg/ansible/controller/controller.go#L60-L73) and [Helm](https://github.com/openshift/ocp-release-operator-sdk/blob/233dbad303edd3e6ad8e40fec92e31552e558319/pkg/helm/controller/controller.go#L60-L66) operators, while upstream does not (see upstream [ansible](https://github.com/operator-framework/operator-sdk/blob/7e07b20c9e22560fb22a3295b612eae7652b8b14/pkg/ansible/controller/controller.go#L62) and [helm](https://github.com/operator-framework/operator-sdk/blob/7e07b20c9e22560fb22a3295b612eae7652b8b14/pkg/helm/controller/controller.go#L59) controllers).

Do we want to align these? There is an upstream PR (operator-framework/operator-sdk#1047) that makes a similar (though not identical) set of changes.

**Comment by shawn-hurley** [comment]
@joelanford I think the PR that is published is the correct way to fix the problem and then we will update this downstream version to match upstream. 

I think this is post 4.1 fix if that is ok with you?

**Comment by joelanford** [comment]
@shawn-hurley Sounds good to me. I'll defer to you about whether we should revert the changes in this repo so that they match operator-sdk. The changes in this repo _look_ harmless enough, but you're more familiar with them than I am.

**Pull request merged**
