### PR TITLE
Bug 2064204:  Apply changes from patch file to go.mod and go.sum BEFORE the patches are applied.

### PR DESCRIPTION
**Pull request by jmrodri**
**Description of the change:**
Apply changes from patch file to go.mod and go.sum BEFORE the patches are applied.

**Motivation for the change:**
Downstream is switching to using cachito to build. It will perform a go list -m which fails because we were patching go.mod and go.sum during build time. This change  applies all of the go.mod and go.sum changes up front.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by asmacdo — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Pull request merged**
