### PR TITLE
OCPBUGS-9399,OCPBUGS-9398,OCPBUGS-9260: Downstream v1.22.2 to release-4.11

### PR DESCRIPTION
**Pull request by everettraven**
Downstreaming of the upstream v1.22.2 release to the release-4.11 branch to resolve the following bugs:
- [OCPBUGS-9399](https://issues.redhat.com/browse/OCPBUGS-9399)
- [OCPBUGS-9398](https://issues.redhat.com/browse/OCPBUGS-9398)
- [OCPBUGS-9260](https://issues.redhat.com/browse/OCPBUGS-9260)

The downstreaming process was mostly automated and done by running:
```
./UPSTREAM_MERGE.sh v1.22.2 release-4.11
```

Manual steps included:
- Updating `patches/03-setversion.patch` to set the version to `v1.22.2-ocp`
- Regenerating the `17-bug2099693-java-bundle-version.patch` as there were some changes to the files this patch was originally made against.

### CODE REVIEW

**Comment by everettraven** [comment]
@emmajiafan @KeenonLee @michaelryanpeter @adellape Would you mind taking a look and add any necessary labels? Thanks!

**Comment by michaelryanpeter** [comment]
Relevant downstream doc work is tracked in OSDOCS-5602
/label docs-approved

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
