### PR TITLE
Merge upstream tag v1.28.0

### PR DESCRIPTION
**Pull request by rashmigottipati**
Operator SDK v1.28.0

Merge executed via ./UPSTREAM-MERGE.sh v1.28.0

### CODE REVIEW

**Comment by rashmigottipati** [comment]
@everettraven Good catch! Updated the `SIMPLE_VERSION` to `v1.28.0-ocp` in latest [bfa002d](https://github.com/openshift/ocp-release-operator-sdk/pull/310/commits/bfa002d277f23db52b87654a2807e84ef66bce0d)

**Review by everettraven — APPROVED** [review]
Changes look good to me! I am holding off on LGTM for now to make sure this doesn't auto-merge before getting QE and Docs approval. I'll keep an eye on it and add an LGTM when needed :)

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
