### PR TITLE
Downstream v1.30.0

### PR DESCRIPTION
**Pull request by everettraven**
Sync with upstream v1.30.0

Done via `./UPSTREAM-MERGE.sh v1.30.0`

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by grokspawn — APPROVED** [review]

**Comment by KeenonLee** [comment]
Hi @everettraven  
opeator sdk version number not updated, please help to check it, thanks ^^
https://issues.redhat.com/browse/OCPBUGS-16138

**Pull request merged**
