### PR TITLE
Bug 1921458: `run bundle-upgrade` should handle error gracefully when a previous operator version doesn't exist

### PR DESCRIPTION
**Pull request by jmrodri**
**Description of the change:**
`run bundle-upgrade` command handles error instead of throwing a panic, when a previous version of the operator bundle doesn't exist in the cluster 

**Motivation for the change:**
```
Without installing etcd operator, 
# operator-sdk run bundle-upgrade quay.io/olmqe/etcd-bundle:0.9.2-share

Result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1978d29]
```

Expected behavior: The command should check that the etcd operator doesn't exist in the cluster and handle the error gracefully instead of throwing a panic.

### CODE REVIEW

**Comment by jmrodri** [comment]
It works
```
$ build/operator-sdk run bundle-upgrade quay.io/olmqe/etcd-bundle:0.9.2-share
FATA[0000] Failed to run bundle upgrade: no existing operator found in the cluster to upgrade 
```

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Comment by theishshah** [comment]
LGTM

**Review by theishshah — APPROVED** [review]
/lgtm

**Pull request merged**
