### PR TITLE
OCPBUGS-1665: [release-4.13] Merge upstream tag v1.28.0 to release-4.13

### PR DESCRIPTION
**Pull request by rashmigottipati**
This PR is to downstream the upstream Operator-SDK v1.28.0 release to the `release-4.13` branch.

### CODE REVIEW

**Comment by KeenonLee** [comment]
Hi @rashmigottipati It looks like the version is 1.27.0
```
jitli@RedHat:~/work/src/github/sdk/downstream/ocp-release-operator-sdk/build$ ./operator-sdk version
operator-sdk version: "v1.27.0-ocp", commit: "05306f5acf1edbbad348b8f3c7a83a031558353a", kubernetes version: "v1.26.0", go version: "go1.19.4", GOOS: "darwin", GOARCH: "arm64"
```

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved
/label cherry-pick-approved

**Review by everettraven — APPROVED** [review]

**Pull request merged**
