### PR TITLE
OCPBUGS-38333: Update admins to add CFE members

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
- Add CFE team members

**Motivation for the change:**
Allow CFE team members to approve and merge PRs

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm
/approve

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Comment by KeenonLee** [comment]
no need docs
/label docs-approved

**Comment by oceanc80** [comment]
no px impact
/label px-approved

**Pull request merged**
