### PR TITLE
OCPBUGS-27807,OCPBUGS-27806,OCPBUGS-27805,OCPBUGS-27810,OCPBUGS-27811,OCPBUGS-27812: bump github.com/go-git/go-git/v5 to v5.11.0

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Bumps github.com/go-git/go-git/v5 to v5.11.0 

**Motivation for the change:**
Addresses the following CVEs:
- https://github.com/advisories/GHSA-mw99-9chc-xw7r
- https://github.com/advisories/GHSA-449p-3h89-pw88

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Pull request merged**
