### PR TITLE
Add darwin/arm64 binaries

### PR DESCRIPTION
**Pull request by yselkowitz**
**Description of the change:**
Add darwin/arm64 to OCP operator-sdk artifacts.

**Motivation for the change:**
The latest MacOS systems are being built with the ARM architecture.

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by yselkowitz** [comment]
images succeeded, which is what matters for this PR.  The other failures do not seem related, and have been failing for some time now.  
/assign @asmacdo

**Comment by jmrodri** [comment]
I did an override of the ansible and helm e2e because they are failing with PSA. That was fixed in master branch. So this PR will be just fine when it merges.

**Pull request merged**
