### PR TITLE
OCPBUGS-23983: Update OCP to 4.15

### PR DESCRIPTION
**Pull request by oceanc80**
**Description of the change:**
Bump OCP version to 4.15

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/approve
/lgtm

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Pull request merged**
