### PR TITLE
Bug 1943698: patch - identification of downstream sdk

### PR DESCRIPTION
**Pull request by varshaprasad96**
**Description of the change:**
identification of downstream sdk

Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>

**Motivation for the change:**

**Checklist**

If the pull request includes user-facing changes, extra documentation is required:
- [ ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [ ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

### CODE REVIEW

**Comment by estroz** [comment]
The version detection code isn't downstreamed, or even merged upstream yet. Why is this being added now? Also, shouldn't the downstream version be differentiated from upstream in all cases?

**Comment by varshaprasad96** [comment]
@estroz since this is downstream specific, it is not being added upstream and is made as a patch here. This is because right now the downstream version has the `-ocp` tag, and the metrics annotations are appearing to be `<sdk_version>+git` instead.

**Comment by jmrodri** [comment]
/retitle Bug 1943698: patch - identification of downstream sdk

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
