### PR TITLE
Add Dockerfile.rhel8

### PR DESCRIPTION
**Pull request by yselkowitz**
**Description of the change:**
Adds a Dockerfile compatible with RHEL 8 content.

**Motivation for the change:**
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.

### CODE REVIEW

**Comment by fabianvf** [comment]
@yselkowitz we were planning on dropping rhel7 support and just updated the Dockerfile to have a ubi8 base, https://github.com/openshift/ocp-release-operator-sdk/blob/master/release/ansible/Dockerfile

**Comment by yselkowitz** [comment]
We're in the process of moving everything to RHEL 8 content on a very short timeline, but to keep the transition smooth for both CI and downstream, using Dockerfile.rhel8 files as needed where backwards incompatible changes are required.

In this case, you can't use the `python-*` package names on RHEL 8 when you really need `python3-*`.  (Ansible Engine and Runner are Python 3 based in RHEL 8.)

**Pull request merged**
