### PR TITLE
Bug 1793307: internal/scaffold: don't change /etc/passwd perms

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
Cherry-pick of : https://github.com/operator-framework/operator-sdk/pull/2469/files

**Motivation**
https://bugzilla.redhat.com/show_bug.cgi?id=1793307
Bug 1793307

### CODE REVIEW

**Comment by joelanford** [comment]
/retitle Bug 1793307: internal/scaffold: don't change /etc/passwd perms [release-4.1]

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley, 

Could you please add here the label  `cherry-pick-approved` or we are able to move forward?

**Comment by camilamacedo86** [comment]
HI @jmrodri, 

Since it is open for too long. When it receives all required label to get the merge starts to face the issue https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ocp-release-operator-sdk/38/pull-ci-openshift-ocp-release-operator-sdk-release-4.1-images/6/build-log.txt which is fixed here in the commit https://github.com/openshift/ocp-release-operator-sdk/pull/38/commits/6292e668bd81f03e533896b5cae84462ef824794. 

Could you please check this one?

**Pull request merged**
